-- Sync production CMS skills with the owner-approved 2026-08 refresh.
--
-- IMPORTANT: run ONLY after the code that knows the new icon_key values is
-- deployed. Older builds crash during SSR when they meet an unknown icon_key
-- (skillIcons[iconKey] used to be unguarded). Safe post-deploy; no-op risk-free
-- fallback: static content already matches this dataset.
--
-- Mirrors src/content/skills.ts exactly (20 tech-stack + 58 others skills,
-- 7 groups incl. Agentic AI sub-sections as categories).

begin;

delete from skill_translations;
delete from skills;

insert into skills (id, group_key, icon_key, url, "order", featured) values
  ('typescript', 'tech-stack', 'typescript', null, 1, true),
  ('javascript', 'tech-stack', 'javascript', null, 2, true),
  ('python', 'tech-stack', 'python', null, 3, false),
  ('nodejs', 'tech-stack', 'nodejs', null, 4, false),
  ('nestjs', 'tech-stack', 'nestjs', null, 5, false),
  ('react', 'tech-stack', 'react', null, 6, true),
  ('nextjs', 'tech-stack', 'nextjs', null, 7, true),
  ('mongodb', 'tech-stack', 'mongodb', null, 8, false),
  ('postgresql', 'tech-stack', 'postgresql', null, 9, false),
  ('mysql', 'tech-stack', 'mysql', null, 10, false),
  ('docker', 'tech-stack', 'docker', null, 11, false),
  ('aws', 'tech-stack', 'aws', null, 12, false),
  ('digitalocean', 'tech-stack', 'digitalocean', null, 13, false),
  ('firebase', 'tech-stack', 'firebase', null, 14, false),
  ('azuredevops', 'tech-stack', 'azuredevops', null, 15, false),
  ('tailwindcss', 'tech-stack', 'tailwindcss', null, 16, false),
  ('scss', 'tech-stack', 'scss', null, 17, false),
  ('wordpress', 'tech-stack', 'wordpress', null, 18, false),
  ('wsl', 'tech-stack', null, null, 19, false),
  ('linux', 'tech-stack', 'linux', null, 20, false),
  ('rest-api', 'others', null, null, 21, false),
  ('clean-architecture', 'others', null, null, 22, false),
  ('dependency-injection', 'others', null, null, 23, false),
  ('api-integration', 'others', null, null, 24, false),
  ('aws-skill', 'others', null, null, 25, false),
  ('digitalocean-skill', 'others', null, null, 26, false),
  ('firebase-skill', 'others', null, null, 27, false),
  ('azure-devops-skill', 'others', null, null, 28, false),
  ('docker-skill', 'others', null, null, 29, false),
  ('vps', 'others', null, null, 30, false),
  ('linux-skill', 'others', null, null, 31, false),
  ('wsl-skill', 'others', null, null, 32, false),
  ('responsive-design', 'others', null, null, 33, false),
  ('web-accessibility', 'others', null, null, 34, false),
  ('performance-optimization', 'others', null, null, 35, false),
  ('core-web-vitals', 'others', null, null, 36, false),
  ('localization', 'others', null, null, 37, false),
  ('technical-seo', 'others', null, null, 38, false),
  ('on-page-seo', 'others', null, null, 39, false),
  ('off-page-seo', 'others', null, null, 40, false),
  ('google-ads', 'others', null, null, 41, false),
  ('wordpress-skill', 'others', null, null, 42, false),
  ('website-architecture', 'others', null, null, 43, false),
  ('keyword-research', 'others', null, null, 44, false),
  ('git', 'others', null, null, 45, false),
  ('github', 'others', null, null, 46, false),
  ('gitlab', 'others', null, null, 47, false),
  ('jira', 'others', null, null, 48, false),
  ('agile-scrum', 'others', null, null, 49, false),
  ('code-review', 'others', null, null, 50, false),
  ('pair-programming', 'others', null, null, 51, false),
  ('cross-functional-collaboration', 'others', null, null, 52, false),
  ('requirement-analysis', 'others', null, null, 53, false),
  ('technical-planning', 'others', null, null, 54, false),
  ('canva', 'others', null, null, 55, false),
  ('adobe-photoshop', 'others', null, null, 56, false),
  ('capcut', 'others', null, null, 57, false),
  ('content-creation', 'others', null, null, 58, false),
  ('visual-design', 'others', null, null, 59, false),
  ('product-presentation', 'others', null, null, 60, false),
  ('digital-content', 'others', null, null, 61, false),
  ('chatgpt', 'others', null, null, 62, false),
  ('claude', 'others', null, null, 63, false),
  ('google-gemini', 'others', null, null, 64, false),
  ('deepseek', 'others', null, null, 65, false),
  ('opencode', 'others', null, null, 66, false),
  ('codex-desktop-cli', 'others', null, null, 67, false),
  ('claude-cli', 'others', null, null, 68, false),
  ('antigravity', 'others', null, null, 69, false),
  ('commandcode', 'others', null, null, 70, false),
  ('openclaw', 'others', null, null, 71, false),
  ('agentic-coding', 'others', null, null, 72, false),
  ('multi-agent-workflows', 'others', null, null, 73, false),
  ('ai-assisted-development', 'others', null, null, 74, false),
  ('context-engineering', 'others', null, null, 75, false),
  ('tool-mcp-integration', 'others', null, null, 76, false),
  ('ai-workflow-orchestration', 'others', null, null, 77, false),
  ('repository-aware-development', 'others', null, null, 78, false);

insert into skill_translations (skill_id, locale, name, category) values
  ('typescript', 'en', 'TypeScript', null),
  ('typescript', 'vi', 'TypeScript', null),
  ('javascript', 'en', 'JavaScript', null),
  ('javascript', 'vi', 'JavaScript', null),
  ('python', 'en', 'Python', null),
  ('python', 'vi', 'Python', null),
  ('nodejs', 'en', 'Node.js', null),
  ('nodejs', 'vi', 'Node.js', null),
  ('nestjs', 'en', 'NestJS', null),
  ('nestjs', 'vi', 'NestJS', null),
  ('react', 'en', 'React', null),
  ('react', 'vi', 'React', null),
  ('nextjs', 'en', 'Next.js', null),
  ('nextjs', 'vi', 'Next.js', null),
  ('mongodb', 'en', 'MongoDB', null),
  ('mongodb', 'vi', 'MongoDB', null),
  ('postgresql', 'en', 'PostgreSQL', null),
  ('postgresql', 'vi', 'PostgreSQL', null),
  ('mysql', 'en', 'MySQL', null),
  ('mysql', 'vi', 'MySQL', null),
  ('docker', 'en', 'Docker', null),
  ('docker', 'vi', 'Docker', null),
  ('aws', 'en', 'AWS', null),
  ('aws', 'vi', 'AWS', null),
  ('digitalocean', 'en', 'DigitalOcean', null),
  ('digitalocean', 'vi', 'DigitalOcean', null),
  ('firebase', 'en', 'Firebase', null),
  ('firebase', 'vi', 'Firebase', null),
  ('azuredevops', 'en', 'Azure DevOps', null),
  ('azuredevops', 'vi', 'Azure DevOps', null),
  ('tailwindcss', 'en', 'Tailwind CSS', null),
  ('tailwindcss', 'vi', 'Tailwind CSS', null),
  ('scss', 'en', 'SCSS', null),
  ('scss', 'vi', 'SCSS', null),
  ('wordpress', 'en', 'WordPress', null),
  ('wordpress', 'vi', 'WordPress', null),
  ('wsl', 'en', 'WSL', null),
  ('wsl', 'vi', 'WSL', null),
  ('linux', 'en', 'Linux', null),
  ('linux', 'vi', 'Linux', null),
  ('rest-api', 'en', 'REST API', 'Architecture'),
  ('rest-api', 'vi', 'REST API', 'Architecture'),
  ('clean-architecture', 'en', 'Clean Architecture', 'Architecture'),
  ('clean-architecture', 'vi', 'Clean Architecture', 'Architecture'),
  ('dependency-injection', 'en', 'Dependency Injection', 'Architecture'),
  ('dependency-injection', 'vi', 'Dependency Injection', 'Architecture'),
  ('api-integration', 'en', 'API Integration', 'Architecture'),
  ('api-integration', 'vi', 'Tích hợp API', 'Architecture'),
  ('aws-skill', 'en', 'AWS', 'DevOps & Infrastructure'),
  ('aws-skill', 'vi', 'AWS', 'DevOps & Infrastructure'),
  ('digitalocean-skill', 'en', 'DigitalOcean', 'DevOps & Infrastructure'),
  ('digitalocean-skill', 'vi', 'DigitalOcean', 'DevOps & Infrastructure'),
  ('firebase-skill', 'en', 'Firebase', 'DevOps & Infrastructure'),
  ('firebase-skill', 'vi', 'Firebase', 'DevOps & Infrastructure'),
  ('azure-devops-skill', 'en', 'Azure DevOps', 'DevOps & Infrastructure'),
  ('azure-devops-skill', 'vi', 'Azure DevOps', 'DevOps & Infrastructure'),
  ('docker-skill', 'en', 'Docker', 'DevOps & Infrastructure'),
  ('docker-skill', 'vi', 'Docker', 'DevOps & Infrastructure'),
  ('vps', 'en', 'VPS', 'DevOps & Infrastructure'),
  ('vps', 'vi', 'VPS', 'DevOps & Infrastructure'),
  ('linux-skill', 'en', 'Linux', 'DevOps & Infrastructure'),
  ('linux-skill', 'vi', 'Linux', 'DevOps & Infrastructure'),
  ('wsl-skill', 'en', 'WSL', 'DevOps & Infrastructure'),
  ('wsl-skill', 'vi', 'WSL', 'DevOps & Infrastructure'),
  ('responsive-design', 'en', 'Responsive Design', 'Frontend & UX'),
  ('responsive-design', 'vi', 'Thiết kế responsive', 'Frontend & UX'),
  ('web-accessibility', 'en', 'Web Accessibility', 'Frontend & UX'),
  ('web-accessibility', 'vi', 'Khả năng tiếp cận web', 'Frontend & UX'),
  ('performance-optimization', 'en', 'Performance Optimization', 'Frontend & UX'),
  ('performance-optimization', 'vi', 'Tối ưu hiệu năng', 'Frontend & UX'),
  ('core-web-vitals', 'en', 'Core Web Vitals', 'Frontend & UX'),
  ('core-web-vitals', 'vi', 'Core Web Vitals', 'Frontend & UX'),
  ('localization', 'en', 'Localization', 'Frontend & UX'),
  ('localization', 'vi', 'Bản địa hóa', 'Frontend & UX'),
  ('technical-seo', 'en', 'Technical SEO', 'SEO & Growth'),
  ('technical-seo', 'vi', 'SEO kỹ thuật', 'SEO & Growth'),
  ('on-page-seo', 'en', 'On-page SEO', 'SEO & Growth'),
  ('on-page-seo', 'vi', 'On-page SEO', 'SEO & Growth'),
  ('off-page-seo', 'en', 'Off-page SEO', 'SEO & Growth'),
  ('off-page-seo', 'vi', 'Off-page SEO', 'SEO & Growth'),
  ('google-ads', 'en', 'Google Ads', 'SEO & Growth'),
  ('google-ads', 'vi', 'Google Ads', 'SEO & Growth'),
  ('wordpress-skill', 'en', 'WordPress', 'SEO & Growth'),
  ('wordpress-skill', 'vi', 'WordPress', 'SEO & Growth'),
  ('website-architecture', 'en', 'Website Architecture', 'SEO & Growth'),
  ('website-architecture', 'vi', 'Kiến trúc website', 'SEO & Growth'),
  ('keyword-research', 'en', 'Keyword Research', 'SEO & Growth'),
  ('keyword-research', 'vi', 'Nghiên cứu từ khóa', 'SEO & Growth'),
  ('git', 'en', 'Git', 'Workflow & Collaboration'),
  ('git', 'vi', 'Git', 'Workflow & Collaboration'),
  ('github', 'en', 'GitHub', 'Workflow & Collaboration'),
  ('github', 'vi', 'GitHub', 'Workflow & Collaboration'),
  ('gitlab', 'en', 'GitLab', 'Workflow & Collaboration'),
  ('gitlab', 'vi', 'GitLab', 'Workflow & Collaboration'),
  ('jira', 'en', 'JIRA', 'Workflow & Collaboration'),
  ('jira', 'vi', 'JIRA', 'Workflow & Collaboration'),
  ('agile-scrum', 'en', 'Agile / Scrum', 'Workflow & Collaboration'),
  ('agile-scrum', 'vi', 'Agile / Scrum', 'Workflow & Collaboration'),
  ('code-review', 'en', 'Code Review', 'Workflow & Collaboration'),
  ('code-review', 'vi', 'Code Review', 'Workflow & Collaboration'),
  ('pair-programming', 'en', 'Pair Programming', 'Workflow & Collaboration'),
  ('pair-programming', 'vi', 'Pair Programming', 'Workflow & Collaboration'),
  ('cross-functional-collaboration', 'en', 'Cross-functional Collaboration', 'Workflow & Collaboration'),
  ('cross-functional-collaboration', 'vi', 'Hợp tác liên bộ phận', 'Workflow & Collaboration'),
  ('requirement-analysis', 'en', 'Requirement Analysis', 'Workflow & Collaboration'),
  ('requirement-analysis', 'vi', 'Phân tích yêu cầu', 'Workflow & Collaboration'),
  ('technical-planning', 'en', 'Technical Planning', 'Workflow & Collaboration'),
  ('technical-planning', 'vi', 'Lập kế hoạch kỹ thuật', 'Workflow & Collaboration'),
  ('canva', 'en', 'Canva', 'Product & Creative'),
  ('canva', 'vi', 'Canva', 'Product & Creative'),
  ('adobe-photoshop', 'en', 'Adobe Photoshop', 'Product & Creative'),
  ('adobe-photoshop', 'vi', 'Adobe Photoshop', 'Product & Creative'),
  ('capcut', 'en', 'CapCut', 'Product & Creative'),
  ('capcut', 'vi', 'CapCut', 'Product & Creative'),
  ('content-creation', 'en', 'Content Creation', 'Product & Creative'),
  ('content-creation', 'vi', 'Sáng tạo nội dung', 'Product & Creative'),
  ('visual-design', 'en', 'Visual Design', 'Product & Creative'),
  ('visual-design', 'vi', 'Thiết kế thị giác', 'Product & Creative'),
  ('product-presentation', 'en', 'Product Presentation', 'Product & Creative'),
  ('product-presentation', 'vi', 'Trình bày sản phẩm', 'Product & Creative'),
  ('digital-content', 'en', 'Digital Content', 'Product & Creative'),
  ('digital-content', 'vi', 'Nội dung số', 'Product & Creative'),
  ('chatgpt', 'en', 'ChatGPT', 'AI Models & Assistants'),
  ('chatgpt', 'vi', 'ChatGPT', 'Mô hình & Trợ lý AI'),
  ('claude', 'en', 'Claude', 'AI Models & Assistants'),
  ('claude', 'vi', 'Claude', 'Mô hình & Trợ lý AI'),
  ('google-gemini', 'en', 'Google Gemini', 'AI Models & Assistants'),
  ('google-gemini', 'vi', 'Google Gemini', 'Mô hình & Trợ lý AI'),
  ('deepseek', 'en', 'DeepSeek', 'AI Models & Assistants'),
  ('deepseek', 'vi', 'DeepSeek', 'Mô hình & Trợ lý AI'),
  ('opencode', 'en', 'OpenCode', 'Agentic Coding & Harness'),
  ('opencode', 'vi', 'OpenCode', 'Agentic Coding & Harness'),
  ('codex-desktop-cli', 'en', 'Codex Desktop / CLI', 'Agentic Coding & Harness'),
  ('codex-desktop-cli', 'vi', 'Codex Desktop / CLI', 'Agentic Coding & Harness'),
  ('claude-cli', 'en', 'Claude CLI', 'Agentic Coding & Harness'),
  ('claude-cli', 'vi', 'Claude CLI', 'Agentic Coding & Harness'),
  ('antigravity', 'en', 'Antigravity', 'Agentic Coding & Harness'),
  ('antigravity', 'vi', 'Antigravity', 'Agentic Coding & Harness'),
  ('commandcode', 'en', 'CommandCode', 'Agentic Coding & Harness'),
  ('commandcode', 'vi', 'CommandCode', 'Agentic Coding & Harness'),
  ('openclaw', 'en', 'OpenClaw', 'Agentic Coding & Harness'),
  ('openclaw', 'vi', 'OpenClaw', 'Agentic Coding & Harness'),
  ('agentic-coding', 'en', 'Agentic Coding', 'AI Development Capabilities'),
  ('agentic-coding', 'vi', 'Agentic Coding', 'Năng lực phát triển AI'),
  ('multi-agent-workflows', 'en', 'Multi-agent Workflows', 'AI Development Capabilities'),
  ('multi-agent-workflows', 'vi', 'Quy trình đa agent', 'Năng lực phát triển AI'),
  ('ai-assisted-development', 'en', 'AI-assisted Development', 'AI Development Capabilities'),
  ('ai-assisted-development', 'vi', 'Phát triển hỗ trợ bởi AI', 'Năng lực phát triển AI'),
  ('context-engineering', 'en', 'Context Engineering', 'AI Development Capabilities'),
  ('context-engineering', 'vi', 'Context Engineering', 'Năng lực phát triển AI'),
  ('tool-mcp-integration', 'en', 'Tool / MCP Integration', 'AI Development Capabilities'),
  ('tool-mcp-integration', 'vi', 'Tích hợp Tool / MCP', 'Năng lực phát triển AI'),
  ('ai-workflow-orchestration', 'en', 'AI Workflow Orchestration', 'AI Development Capabilities'),
  ('ai-workflow-orchestration', 'vi', 'Điều phối quy trình AI', 'Năng lực phát triển AI'),
  ('repository-aware-development', 'en', 'Repository-aware Development', 'AI Development Capabilities'),
  ('repository-aware-development', 'vi', 'Phát triển gắn với repository', 'Năng lực phát triển AI');

-- Stable taxonomy keys on the base rows (mirrors migration
-- 20260823090000_skill_category_keys.sql; labels stay code-owned).
update skills s
set category_key = case t.category
  when 'Architecture' then 'architecture'
  when 'DevOps & Infrastructure' then 'devops-infrastructure'
  when 'Frontend & UX' then 'frontend-ux'
  when 'SEO & Growth' then 'seo-growth'
  when 'Workflow & Collaboration' then 'workflow-collaboration'
  when 'Product & Creative' then 'product-creative'
  when 'AI Models & Assistants' then 'ai-models-assistants'
  when 'Agentic Coding & Harness' then 'agentic-coding-harness'
  when 'AI Development Capabilities' then 'ai-development-capabilities'
  else null
end
from skill_translations t
where t.skill_id = s.id
  and t.locale = 'en'
  and s.group_key = 'others';

commit;
